### ISSUE TITLE
How to connect ELK with OSSEC ?

### ISSUE THREAD

**Issue by gagantous** [ossec/ossec-hids#1376]
i have read and tried this tutorial

https://practicalassurance.com/blog/ossec-elk-stack-integration/
But it didnt catch the ossec log (alerts, syslog, etc), it just give me this message for my Kibana apps.

> Couldn't find any Elasticsearch data
> You'll need to index some data into Elasticsearch before you can create an index pattern.

I know that there is some tutorial like below
https://wazuh.com/elastic-stack/

But it's need wazuh package and i dont want to used wazuh app, i just want to use the pure OSSEC. 

Is there tutorial where i can integrated OSSEC with ELK for the currect apps ?

**Comment by ddpbsd** [comment]
I've been playing with this a little bit lately. I think I have some information on it in a pull request to the documentation, but it's not ready yet. It's not a tutorial, but here's a basic run-down of what I'm currently trying.
For my setup, I turned on json alerts in the OSSEC server's ossec.conf
```
<global>
      <jsonout_output>yes</jsonout_output>
</global>
```

Then I use filebeat on the OSSEC server to read `/var/ossec/logs/alerts/alerts.json` and forward them to logstash:
```
- input_type: log
  paths:
    - /var/ossec/logs/alerts/alerts.json
  fields:
    log_type: ossec
  json.keys_under_root: true
output.logstash:
  hosts: ["elastic:9001"]
```

Current logstash configuration (there's some extra stuff in here you won't necessarily need):
```
input {
  beats {
    id => "beats_test"
    port => 9001
  }
}
filter {
  if([fields][log_type] == "ossec") {
    mutate {
      replace => {
        "[type]" => "osseclogs"
      }
    }
  } 
}
output {

  if([type] == "osseclogs") {
    elasticsearch {
      index => "ossec-%{+YYYY.MM.dd}"
    }
  }
}
```

**Comment by gagantous** [comment]
@ddpbsd  
Why we use `elastic:9001` ? i thought `9200`

**Comment by gagantous** [comment]
What kind of architecture model that you used for your ossec ? is it `Single-Host` architecture ( OSSEC and ELK are in the same machine ) or `Distributed` Architecture (OSSEC and ELK are installed in each seperated machine )  ? 

@ddpbsd

**Comment by gagantous** [comment]
@ddpbsd which .conf should i change ? which `logstash.conf` ?

**Comment by gagantous** [comment]
and why i have to used filebeat first ?

**Comment by gagantous** [comment]
@ddpbsd  okay ihave installed filebeat, but i dont know how to use this...

**Comment by ddpbsd** [comment]
9001 was arbitrary. Use whichever you want. I think elasticsearch defaults to 9200 though. 
Elk and ossec are on different machines.
The logstash config I posted went in `/etc/logstash/conf.d`
Filebeat feeds the data to logstash. You could use logstash directly, or even json csyslogd output. I wanted to try filebeat.
I did no other configuration. In kibana, go to configure or management or something on the left menu. Then to templates. I let it figure everything out.

**Comment by gagantous** [comment]
@ddpbsd 

How did you learn that ? i mean installation, configuration for OSSEC and ELK and  such ?

**Comment by ddpbsd** [comment]
I read the documentation for the various projects and experimented.

**Comment by gagantous** [comment]
@ddpbsd 

Is the conft same location with `/etc/logstash/conf.d`

```
- input_type: log
  paths:
    - /var/ossec/logs/alerts/alerts.json
  fields:
    log_type: ossec
  json.keys_under_root: true
output.logstash:
  hosts: ["elastic:9001"]
```
