### ISSUE TITLE
/var/ossec/etc/ossec.conf and Ansible community.general.xml

### ISSUE THREAD

**Issue by fcorneli** [ossec/ossec-hids#2102]
When provisioning OSSEC via Ansible using the `community.general.xml` module, this module adds
```xml
<?xml version="1.0" encoding="utf-8"?>
```
on top of the -what should be- XML configuration file.
However, the OSSEC XML parser fails on this.

Right now I have to apply the following rather painful work-around (CentOS 7):
```yaml
- name: Install required tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - libxml2
    - epel-release
    - moreutils
- name: Sanitize ossec.conf
  ansible.builtin.shell: set -o pipefail && /usr/bin/xmllint -c14n /var/ossec/etc/ossec-server.conf | /usr/bin/sponge /var/ossec/etc/ossec-server.conf
```
Could the OSSEC XML config parser be fixed to simply ignore such XML declarations?
